### ISSUE TITLE
Get Access to Finance Codes from Finance Database

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/controller-data-scraper#4]
Instead of scraping the finance codes from their website, we can connect to the actual finance system database and grab the data we need.

**Comment by johnclary** [comment]
We need this for Warehouse Inventory, because we need task order fund information that is not available on the website we're scraping.

I'm in touch with the controller's office to get the views setup.

**Comment by johnclary** [comment]
cc @dianamartin

**Comment by johnclary** [comment]
Just provided the view definitions to Phil K. they're attached.


> Phil—attached xlsx has a column for each item we need access to, with the field names listed below it.
>
>  Objects, units, and task orders can be filtered for dept 2400.
>
> Regarding task orders, the "Type", "Current Allocation", and "Balance" are fields that we have seen in eCapris, but not on the controller's office website. The rest of the views should match exactly what can be found by searching here:
http://finance.austintexas.gov/web/controller/Home/acctlookuphome.cfm

[fieldnames](https://app.zenhub.com/files/140850398/c83a71b7-d6b4-43f4-884a-71e950714099/download)

**Comment by johnclary** [comment]
The views have been created in prod and we have DB credentials. Will try to connect and inspect the views, then this can be closed.

**Comment by amenity** [comment]
@johnclary - sounds like this can be pushed to Review/QA?

**Comment by johnclary** [comment]
@SurbhiBakshi confirmed we now have DB access. Yay. Closing.
